proxyCommand:
  - /entrypoint.sh
  - --log.level=DEBUG
  - --api.insecure=true
  - --api.dashboard=false
  - --providers.docker=true
  - --entrypoints.https.address=:443
  - --entrypoints.https.transport.respondingTimeouts.readTimeout=10m
  - --entrypoints.http.address=:80
  - --providers.docker.exposedbydefault=false
  - --providers.file.directory=/proxy_config
  - --providers.file.watch=true
