import type { Quad, Term } from '@rdfjs/types'
import { Collection, IriTemplate } from '@rdfine/hydra'
import { AnyPointer, GraphPointer } from 'clownface'
import { rdf } from '@tpluscode/rdf-ns-builders'
import * as ns from '@cube-creator/core/namespace'
import { loadResourceLabels as _loadResourceLabels } from '../queries/observations'
import { warning } from '../../log'
import { createSource, createView, createHydraCollection, populateFilters, buildOptimizedObservationsQuery, buildOptimizedCountQuery, mapObservationRows } from './lib'

const DEFAULT_PAGE_SIZE = 20
const DEFAULT_PAGE_INDEX = 1

interface Params {
  cubeId: string
  sourceGraph: string
  templateParams: GraphPointer
  template: IriTemplate
  filters?: AnyPointer
  pageSize?: number
  pageIndex?: number
  loadResourceLabels?: (ids: Term[]) => Promise<Quad[]>
}

export async function getObservations({
  cubeId,
  sourceGraph,
  filters,
  templateParams,
  template,
  pageSize = DEFAULT_PAGE_SIZE,
  pageIndex = DEFAULT_PAGE_INDEX,
  loadResourceLabels = _loadResourceLabels,
}: Params): Promise<Collection> {
  const source = createSource(sourceGraph)

  const cubes = await source.cubes()
  const cube = cubes.find(({ ptr }) => ptr.value === cubeId)
  if (!cube) {
    warning(`Cube not found: '${cubeId}'`)
    return createHydraCollection({
      observations: [],
      templateParams,
      template,
      totalItems: 0,
      pageSize,
    })
  }

  const offset = pageSize * (pageIndex - 1)
  const view = createView(cube, pageSize, offset)
  if (filters) {
    populateFilters(view, filters)
  }

  let observations: Record<string, Term>[]
  let totalItems: number

  // Use an optimized query when no filters are active. The default query generated by
  // rdf-cube-view-query puts all dimension patterns in a single GRAPH block, which causes
  // GraphDB to decompose it into per-triple optimization groups and perform a full
  // cross-join before applying ORDER BY/LIMIT. The optimized variant moves the ORDER BY
  // dimension into an inner sub-SELECT so GraphDB can apply top-N pruning early, then
  // resolves the remaining dimensions via cheap point-lookups in an outer GRAPH block.
  //
  // The guard on `observationsQuery` being callable lets the test stubs stay as-is
  // (they return { observations, observationCount } without this method).
  if (!filters && typeof (view as any).observationsQuery === 'function') {
    const viewQuery = view.observationsQuery({ disableDistinct: true })
    const client = (cube.source as any).client
    const queryOperation = (cube.source as any).queryOperation

    const obsRows: any[] = await client.query.select(
      buildOptimizedObservationsQuery(viewQuery),
      { operation: queryOperation },
    )
    observations = mapObservationRows(obsRows, viewQuery)

    const countRows: any[] = await client.query.select(
      buildOptimizedCountQuery(viewQuery),
      { operation: queryOperation },
    )
    totalItems = countRows.length > 0 ? parseInt(countRows[0].count.value) : 0
  } else {
    // Fallback: filters are active (they already narrow the result set, so the
    // default query is fast enough) or running under test stubs.
    observations = await view.observations({ disableDistinct: true })
    totalItems = await view.observationCount({ disableDistinct: true })
  }

  const collection = createHydraCollection({
    observations,
    templateParams,
    template,
    totalItems,
    pageSize,
  })

  // Load labels for linked resources
  const labelQuads = await getLabels(observations, loadResourceLabels)
  labelQuads.forEach((quad) => collection.pointer.dataset.add(quad))

  return collection
}

async function getLabels(observations: Record<string, Term>[], loadResourceLabels: (ids: Term[]) => Promise<Quad[]>): Promise<Quad[]> {
  const blackList: string[] = [rdf.type.value, ns.cube.observedBy.value]
  const resourceIds = new Set(observations.flatMap((observation) => {
    return Object.entries(observation)
      .filter(([key, value]) => !blackList.includes(key) && value.termType === 'NamedNode')
      .map(([, value]) => value)
  }))

  return loadResourceLabels([...resourceIds])
}
