name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Prepeare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install --frozen-lockfile --ignore-scripts

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: "chore: release"
          title: "Merge to release"

  tags:
    name: Create tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tag Core API
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: apis/core
          tag_prefix: lindas-cube-creator-api/v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag UI
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: ui
          tag_prefix: lindas-cube-creator-app/v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag CLI
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: cli
          tag_prefix: lindas-cube-creator-cli/v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
